name: PR Preview
on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: job-url
        with:
          script: |
              const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
                ...context.repo,
                run_id: context.runId,
                attempt_number: process.env.GITHUB_RUN_ATTEMPT,
              });

              return data.jobs[0].html_url
          result-encoding: string

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          logs: ${{ steps.job-url.outputs.result }}
          env: preview-${{ github.event.pull_request.number }}
          
      - run: echo perform deploy

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          logs: ${{ steps.job-url.outputs.result }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}

          env_url: https://pr-preview-${{ github.event.pull_request.number }}.example.com
