name: PR Preview Cleanup
on:
  pull_request:
    types: [ closed ]
  
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - run: echo shutdown deployment

      - name: mark environment as deactivated
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview-${{ github.event.pull_request.number }}
          desc: PR was closed

      - name: Get token
        uses: tibdex/github-app-token@v1.8.0
        id: token
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: delete environment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ steps.token.outputs.token }}
          env: preview-${{ github.event.pull_request.number }}
          desc: PR was closed
